title: Recrut Talent
email: viraj.chaudhary@apexure.com
description: >-
  Recruitment and Business Solutions - Built on Intelligence and driven by Passion
meta-keywords:
baseurl: "/RT-testing"
url: "https://virajchuaudhary.github.io"
#site variables
favicon: "/images/favicon.svg"
footer-phone-number: +1 (888) 797-8728
footer-email: infohr@recruittalent.com
footer-address: "RecruitTalent
  8565 Sudley Rd, Suite C
  Manassas, VA 20110, USA"
# collections
collections:
  Services:
    title: Services
    output: true
    permalink: /Services/:name
  testimonials:
    title: Testimonials
    output: true  
  case-studies:
    title: Case Studies
    output: true
# default values
defaults:
  - scope:
      path: ""
      type: "Services"
    values:
      layout: single-service
      title: 
      description: 
      sub-heading: 
      short-description: |-

      social-image:
      permalink: 
      card-icon-image: 
      card-thumbnail-image: 
      button-text:
      is-visible-on-home-page: true
      order: 
      banner-image: 
      banner-button-text: 
      banner-button-link: 
      second-section-left-image: 
      second-section-left-image-alt: 
      second-section-right-heading: 
      second-section-right-description: |- 

      second-section-button-text: 
      second-section-button-link: 
      third-section-heading: 
      third-section-client-company-logos:
      - "/images/circle.svg"
      - "/images/hexa.svg"
      - "/images/treva.svg"
      - "/images/yourlogo.svg"
      - "/images/dummies.svg"
      testimonial-section-top-image: "/images/5stars.svg"
      testimonial-section-heading: "What Our Clients Say"
  - scope:
      path: ""
      type: posts
    values:    
      layout: post
      title: 
      description: 
      short-description: 
      permalink: 
      order: 
      card-thumbnail-image: 
      short-image: 
      feature-image:
      category: 
      button-text: 
      latest-blog-section-heading: "Our Latest Blog"
      latest-blog-section-button-text: "VIEW ALL POSTS"
      latest-blog-section-button-link: "/blog/"
      social-share-heading: Share This Post On 
      author-name: 
      author-image: 
      author-designation: 
      author-facebook-link:  
      author-instagram-link: 
      author-linkedin-link: 
      author-twitter-link: 
      author-section-heading: 
      form-heading: Download 2022 List FREE
      author-description: |-
#Blog pagination
# pagination:
#   enabled: true
#   per_page: 3
#   offset: 0
#   permalink: "/page-:num/"
#   title: ":title - page :num of :max"
#   limit: 0
#   sort_field: date
#   sort_reverse: true
permalink: "/blog/:title/"     
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
#sass
sass:
  sass_dir: _sass
  style: compressed
# exclude
exclude:
  - Gemfile.lock
  - node_modules/
